name: quiver
version: 0.7.0
authors:
- Justin Fagnani <justinfagnani@google.com>
- Yegor Jbanov <yjbanov@google.com>
description: A set of utility libraries for Dart
homepage: https://github.com/google/quiver-dart
dependencies:
  path: ">=0.6.17+2 <0.7.0"
dev_dependencies:
  unittest: any
